# Generated by Django 5.0.8 on 2025-01-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidmember',
            name='failed_payment',
            field=models.BooleanField(default=False),
        ),
    ]
