# Generated by Django 5.0.8 on 2025-01-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_paidmember_failed_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_month_price', models.IntegerField(default=0)),
                ('three_month_price', models.IntegerField(default=0)),
                ('twelve_month_price', models.IntegerField(default=0)),
            ],
        ),
    ]
