# Generated by Django 4.1.3 on 2025-03-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_globalprices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Globals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_month_price', models.IntegerField(default=0)),
                ('three_month_price', models.IntegerField(default=0)),
                ('twelve_month_price', models.IntegerField(default=0)),
                ('user_count', models.IntegerField(default=0)),
                ('courses_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='GlobalPrices',
        ),
    ]
