# Generated by Django 5.1.6 on 2025-03-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_globals_delete_globalprices'),
    ]

    operations = [
        migrations.AddField(
            model_name='globals',
            name='stripe_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globals',
            name='vsl_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
